# Generated by Django 5.1.6 on 2025-02-15 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipe_author_alter_recipe_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='cooking_time',
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часы приготовления'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='cooking_minutes',
            field=models.PositiveIntegerField(default=0, verbose_name='Минуты приготовления'),
        ),
    ]
