# Generated by Django 5.1.6 on 2025-02-15 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_recipe_cooking_time_recipe_cooking_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='author',
            field=models.CharField(max_length=255, verbose_name='Автор'),
        ),
    ]
